# Generated by Django 5.2.17 on 2026-09-10 17:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'insurance type',
                'verbose_name_plural': 'insurance types',
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='insurers_insurancetype_name_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='contact phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
            options={
                'verbose_name': 'insurer',
                'verbose_name_plural': 'insurers',
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='insurers_insurer_name_ci_uniq')],
            },
        ),
    ]
