# Generated by Django 5.2.17 on 2026-09-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('PROPERTY', 'Property'), ('VEHICLE', 'Vehicle'), ('PERSON', 'Person'), ('COMPANY', 'Company'), ('OTHER', 'Other')], max_length=16, verbose_name='object type')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='description')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'insured object',
                'verbose_name_plural': 'insured objects',
                'ordering': ['label', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('object_type__in', ['PROPERTY', 'VEHICLE', 'PERSON', 'COMPANY', 'OTHER'])), name='policies_insuredobject_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, verbose_name='policy number')),
                ('coverage_start', models.DateField(verbose_name='coverage start')),
                ('coverage_end', models.DateField(verbose_name='coverage end')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16, verbose_name='status')),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='premium')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='currency')),
                ('notes', models.CharField(blank=True, max_length=2000, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurancetype', verbose_name='insurance type')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurer', verbose_name='insurer')),
                ('previous_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_policies', to='policies.policy', verbose_name='previous policy')),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
                'ordering': ['coverage_end', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('insured_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_links', to='policies.insuredobject', verbose_name='insured object')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_objects', to='policies.policy', verbose_name='policy')),
            ],
            options={
                'verbose_name': 'policy object',
                'verbose_name_plural': 'policy objects',
                'ordering': ['policy_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('POLICYHOLDER', 'Policyholder'), ('INSURED', 'Insured'), ('PAYER', 'Payer')], max_length=16, verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_parties', to='customers.customer', verbose_name='customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='policies.policy', verbose_name='policy')),
            ],
            options={
                'verbose_name': 'policy party',
                'verbose_name_plural': 'policy parties',
                'ordering': ['policy_id', 'role', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_end__gte', models.F('coverage_start'))), name='policies_policy_coverage_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('premium__isnull', True), ('premium__gte', 0), _connector='OR'), name='policies_policy_premium_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'EXPIRED', 'RENEWED', 'CANCELLED'])), name='policies_policy_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('previous_policy__isnull', True), models.Q(('previous_policy', models.F('id')), _negated=True), _connector='OR'), name='policies_policy_previous_not_self'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_policy__isnull', False)), fields=('previous_policy',), name='policies_policy_previous_policy_uniq'),
        ),
        migrations.AddConstraint(
            model_name='policyobject',
            constraint=models.UniqueConstraint(fields=('policy', 'insured_object'), name='policies_policyobject_policy_object_uniq'),
        ),
        migrations.AddConstraint(
            model_name='policyparty',
            constraint=models.UniqueConstraint(fields=('policy', 'customer', 'role'), name='policies_policyparty_policy_customer_role_uniq'),
        ),
        migrations.AddConstraint(
            model_name='policyparty',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['POLICYHOLDER', 'INSURED', 'PAYER'])), name='policies_policyparty_role_valid'),
        ),
    ]
