# Generated by Django 5.2.17 on 2026-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company')], max_length=16, verbose_name='customer type')),
                ('display_name', models.CharField(max_length=255, verbose_name='display name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['display_name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('customer_type__in', ['PERSON', 'COMPANY'])), name='customers_customer_type_valid')],
            },
        ),
    ]
