# Generated by Django 5.2.17 on 2026-09-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('target_type', models.CharField(max_length=100, verbose_name='target type')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='target id')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='summary')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='occurred at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['occurred_at'], name='audit_event_occurred_at_idx'), models.Index(fields=['action'], name='audit_event_action_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_event_target_idx'), models.Index(fields=['actor'], name='audit_event_actor_idx')],
            },
        ),
    ]
